### PR TITLE
Add FF Support

### PR DESCRIPTION
**Pull request by nicholasmullikin**
Hello!
I just discovered this add-on and love it! I wanted to use it on firefox, so I added a new build option for that. Unfortunately, I wasn't able to reuse the same manifest for both due to the background field being incompatible. I'm not really sure about best practices for multi browser support, so I just added more build options.

### CODE REVIEW

**Comment by Willxiam** [comment]
very cool @nicholasmullikin

**Comment by iansinnott** [comment]
Thanks for this @nicholasmullikin! Regarding best practice for manifest files, having separate files is fine even if not ideal. Another option would be to have a transform the manifest via script to accommodate a specific browser. I had da script to do this early on so that it would build for both mv2 and mv3. it's fine to have separate files though.

However, how will this work? 

The extension's runtime code still uses chrome-specific APIs (ex: https://github.com/iansinnott/full-text-tabs-forever/blob/master/src/background.ts#L91). Unless FF has a built-in compatibility layer then the extension will still not run in FF.

**Comment by nicholasmullikin** [comment]
On manifest files: Yeah that sounds good to me. Happy to keep them separate.

Chrome APIs: I believe one of the packages must be providing a compatibility layer, but I'm not sure which one. When I inspect the extension and use the attached console, I am able to use the chrome API. I'm not quite sure exactly how this works though.
image

**Comment by iansinnott** [comment]
> must be providing a compatibility layer,

Interesting. Yeah I'd like to know the answer here but no need to find out before shipping. Thanks!

**Pull request merged**
